TIMEOUT 30
DEFAULT mini-linux-a

LABEL mini-linux-a
    MENU LABEL Mini Linux slot A
    KERNEL /Image
    FDT /board.dtb
    APPEND console=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=squashfs ro rootwait data=/dev/mmcblk0p4

LABEL mini-linux-b
    MENU LABEL Mini Linux slot B
    KERNEL /Image
    FDT /board.dtb
    APPEND console=ttyAMA0,115200 root=/dev/mmcblk0p3 rootfstype=squashfs ro rootwait data=/dev/mmcblk0p4

